# Generated by Django 4.2.4 on 2023-09-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
